---
# tasks file for apache-maven

- name: Check if desired Maven version is installed
  ansible.builtin.stat:
    path: "{{ maven_home_parent_directory }}/apache-maven-{{ maven_version }}"
  register: maven_dir

- name: Install or update Maven
  block:

    - name: Download Maven checksum file
      ansible.builtin.get_url:
        url: "{{ maven_download_url }}.sha512"
        dest: "/tmp/{{ maven_file_name }}.sha512"
        mode: "0644"

    - name: Read Maven checksum
      ansible.builtin.slurp:
        src: "/tmp/{{ maven_file_name }}.sha512"
      register: maven_checksum_file

    - name: Set Maven checksum fact
      ansible.builtin.set_fact:
        maven_checksum: "{{ maven_checksum_file.content | b64decode | trim }}"

    - name: Download Maven archive
      ansible.builtin.get_url:
        url: "{{ maven_download_url }}"
        dest: "{{ maven_home_parent_directory }}/{{ maven_file_name }}"
        checksum: "sha512:{{ maven_checksum }}"
        mode: "0644"

    - name: Extract Maven
      ansible.builtin.unarchive:
        src: "{{ maven_home_parent_directory }}/{{ maven_file_name }}"
        dest: "{{ maven_home_parent_directory }}"
        remote_src: true
        creates: "{{ maven_home_parent_directory }}/apache-maven-{{ maven_version }}"

    - name: Install Maven profile script
      ansible.builtin.template:
        src: "maven.sh.j2"
        dest: "/etc/profile.d/maven.sh"
        owner: root
        group: root
        mode: "0644"

    - name: Remove downloaded archive
      ansible.builtin.file:
        path: "{{ maven_home_parent_directory }}/{{ maven_file_name }}"
        state: absent

    - name: Remove temporary checksum file
      ansible.builtin.file:
        path: "/tmp/{{ maven_file_name }}.sha512"
        state: absent

  when: not maven_dir.stat.exists

