FROM ubuntu:22.04
USER root

RUN sed -i -e 's/^APT/# APT/' -e 's/^DPkg/# DPkg/' \
      /etc/apt/apt.conf.d/docker-clean

RUN \
    export DEBIAN_FRONTEND=noninteractive && \
        apt-get update && \
        apt-get upgrade -y 
