FROM ubuntu:20.04



RUN \
  apt-get update && \
  apt-get install -y ansible

# Install Ansible inventory file
RUN echo "[local]\nlocalhost ansible_connection=local" > /etc/ansible/hosts

ENTRYPOINT dumb-init python -c 'while True: pass'
