FROM ubuntu:16.04
RUN apt-get update

# Install Ansible
RUN apt-get install -y ansible=2.0.0.2-2

# Install Ansible inventory file
RUN echo "[local]\nlocalhost ansible_connection=local" > /etc/ansible/hosts
