FROM ubuntu:22.04

# fix for E: Problem executing scripts APT::Update::Post-Invoke 'rm -f /var/cache/apt/archives/*.deb /var/cache/apt/archives/partial/*.deb /var/cache/apt/*.bin || true'
# https://stackoverflow.com/a/71982514
USER root
RUN sed -i -e 's/^APT/# APT/' -e 's/^DPkg/# DPkg/' \
      /etc/apt/apt.conf.d/docker-clean

RUN \
    export DEBIAN_FRONTEND=noninteractive && \
        apt-get update && \
        apt-get upgrade -y && \
        apt-get install -y \
            build-essential \
            python3-dev \
            python3-pip \
            software-properties-common \
            git \
            gpg-agent \
            && \
        pip3 install dumb-init && \
        apt-get remove -y \
            build-essential \
            python3-dev \
            python3-pip \
            && \
        apt-get autoremove -y && \
        apt-get clean && \
        rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* && \
        :


RUN \
    export DEBIAN_FRONTEND=noninteractive && \
    apt-add-repository -y ppa:ansible/ansible && \
    apt-get update && \
    apt-get install -y --no-install-recommends ansible

# Install Ansible inventory file
RUN echo "[local]\nlocalhost ansible_connection=local" > /etc/ansible/hosts

ENTRYPOINT dumb-init python3 -c 'while True: pass'
