---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: org.tecris/ubuntu.22.04-jdk:23.03.26
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: testinfra
