ARG TAG
FROM org.tecris/ubuntu_20.04-systemd:${TAG}


ARG jdk_version
ARG jdk_version_patch

ADD OpenJDK21U-jdk_x64_linux_hotspot_${jdk_version}_${jdk_version_patch}.tar.gz /opt
RUN echo "export JAVA_HOME=/opt/jdk-${jdk_version}+${jdk_version_patch}" > /etc/profile.d/java.sh
RUN echo "PATH=/opt/jdk-${jdk_version}+${jdk_version_patch}/bin:${PATH}" >> /etc/profile.d/java.sh
