---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint .
platforms:
  - name: instance
    image: org.tecris/ubuntu-20.04-jdk:23.03.26
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: testinfra
  additional_files_or_dirs:
    - ../../resources/tests
